# Generated by Django 4.2.4 on 2023-08-15 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('payments', '0002_alter_payments_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='customer.customers'),
        ),
    ]
