# Generated by Django 4.2.4 on 2023-08-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payments_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_details',
            field=models.TextField(default='Mpesa'),
        ),
        migrations.AddField(
            model_name='payments',
            name='sign_off',
            field=models.TextField(default='owner'),
        ),
    ]
